; Deathrun
deathrun_player_database.amxx			; Load Player Data
deathrun_map_database.amxx				; Automatic map installer
deathrun_recordmen.amxx					; Recordmen HUD Message
deathrun_player_rank.amxx				; Player Rank
deathrun_player_id.amxx					; Player ID
deathrun_timer.amxx						; Timer
deathrun_bots.amxx						; Bots	